apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - port: 9090
    nodePort: 30003
    targetPort: web
    protocol: TCP
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  type: NodePort
