global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
      monitor: 'Primary'

# rule_files:
#   - /prometheus/alert.rules

# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'federation'
    scrape_interval: 30s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets:
          - "localhost:30900"

  # - job_name: "svr-1"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]    

  # - job_name: "docker"
  #   static_configs:
  #     - targets: ["host.docker.internal:9323"]

  # - job_name: "cAdvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8080"] 
      
  # - job_name: "k8s-metric-svr"
  #   static_configs:
  #     - targets: ["10.43.198.126:8080"]    
