apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local
spec:
  #add from a forum      
  # storageClassName: managed-nfs-storage      
  ###
  storageClassName: local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /root/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master        
          - hamid    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-local
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
