apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
    name: app
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: app-port
    interval: 60s
    scrapeTimeout: 30s
    path: /metrics
  selector:
    matchLabels:
      name: app     