kind: Service
apiVersion: v1
metadata:
  name: prometheus-np
  namespace: monitor
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
    # namespace: monitor
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
