kind: Service
apiVersion: v1
metadata:
  name: prometheus-np
spec:
  selector:
    app.kubernetes.io/instance: demo-1
    app.kubernetes.io/name: prometheus
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30009
