#chown nobody:nogroup /nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs
    path: /nfs

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-prom-prometheus-0
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs
#   nfs:
#     server: nfs
#     path: /nfs