apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs
    path: /nfs

