global:
  scrape_interval: 1m
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: hosted-svr
    static_configs:
      - targets: ['10.10.10.10:9100']
  - job_name: cadvisor
    static_configs:
      - targets: ['10.10.10.10:8080']
